package net.netasystems.client.persistence.entities;
// Generated 27/09/2018 11:28:55 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatalogoGeneral generated by hbm2java
 */
@Entity
@Table(name = "catalogo_general", schema = "public")
public class CatalogoGeneral implements java.io.Serializable {

	private int idCatalogo;
	private Integer idTipoCatalogo;
	private String valCatalogo;
	private String descCatalogo;
	private int idEstatus;
	private String usrCrea;
	private Date fchCrea;
	private String usrModi;
	private Date fchModi;
	private Set<IdentificacionOficial> identificacionOficials = new HashSet<IdentificacionOficial>(0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<IdentificacionesCliente> identificacionesClientes = new HashSet<IdentificacionesCliente>(0);

	public CatalogoGeneral() {
	}

	public CatalogoGeneral(int idCatalogo, String valCatalogo, int idEstatus) {
		this.idCatalogo = idCatalogo;
		this.valCatalogo = valCatalogo;
		this.idEstatus = idEstatus;
	}

	public CatalogoGeneral(int idCatalogo, Integer idTipoCatalogo, String valCatalogo, String descCatalogo,
			int idEstatus, String usrCrea, Date fchCrea, String usrModi, Date fchModi,
			Set<IdentificacionOficial> identificacionOficials, Set<Cliente> clientes,
			Set<IdentificacionesCliente> identificacionesClientes) {
		this.idCatalogo = idCatalogo;
		this.idTipoCatalogo = idTipoCatalogo;
		this.valCatalogo = valCatalogo;
		this.descCatalogo = descCatalogo;
		this.idEstatus = idEstatus;
		this.usrCrea = usrCrea;
		this.fchCrea = fchCrea;
		this.usrModi = usrModi;
		this.fchModi = fchModi;
		this.identificacionOficials = identificacionOficials;
		this.clientes = clientes;
		this.identificacionesClientes = identificacionesClientes;
	}

	@Id

	@Column(name = "id_catalogo", unique = true, nullable = false)
	public int getIdCatalogo() {
		return this.idCatalogo;
	}

	public void setIdCatalogo(int idCatalogo) {
		this.idCatalogo = idCatalogo;
	}

	@Column(name = "id_tipo_catalogo")
	public Integer getIdTipoCatalogo() {
		return this.idTipoCatalogo;
	}

	public void setIdTipoCatalogo(Integer idTipoCatalogo) {
		this.idTipoCatalogo = idTipoCatalogo;
	}

	@Column(name = "val_catalogo", nullable = false, length = 20)
	public String getValCatalogo() {
		return this.valCatalogo;
	}

	public void setValCatalogo(String valCatalogo) {
		this.valCatalogo = valCatalogo;
	}

	@Column(name = "desc_catalogo", length = 50)
	public String getDescCatalogo() {
		return this.descCatalogo;
	}

	public void setDescCatalogo(String descCatalogo) {
		this.descCatalogo = descCatalogo;
	}

	@Column(name = "id_estatus", nullable = false)
	public int getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(int idEstatus) {
		this.idEstatus = idEstatus;
	}

	@Column(name = "usr_crea", length = 20)
	public String getUsrCrea() {
		return this.usrCrea;
	}

	public void setUsrCrea(String usrCrea) {
		this.usrCrea = usrCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_crea", length = 35)
	public Date getFchCrea() {
		return this.fchCrea;
	}

	public void setFchCrea(Date fchCrea) {
		this.fchCrea = fchCrea;
	}

	@Column(name = "usr_modi", length = 20)
	public String getUsrModi() {
		return this.usrModi;
	}

	public void setUsrModi(String usrModi) {
		this.usrModi = usrModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_modi", length = 35)
	public Date getFchModi() {
		return this.fchModi;
	}

	public void setFchModi(Date fchModi) {
		this.fchModi = fchModi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoGeneral")
	public Set<IdentificacionOficial> getIdentificacionOficials() {
		return this.identificacionOficials;
	}

	public void setIdentificacionOficials(Set<IdentificacionOficial> identificacionOficials) {
		this.identificacionOficials = identificacionOficials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoGeneral")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoGeneral")
	public Set<IdentificacionesCliente> getIdentificacionesClientes() {
		return this.identificacionesClientes;
	}

	public void setIdentificacionesClientes(Set<IdentificacionesCliente> identificacionesClientes) {
		this.identificacionesClientes = identificacionesClientes;
	}

}
