package net.netasystems.client.persistence.entities;
// Generated 27/09/2018 11:28:55 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdentificacionesClienteId generated by hbm2java
 */
@Embeddable
public class IdentificacionesClienteId implements java.io.Serializable {

	private int idCliente;
	private int idIdentificacion;

	public IdentificacionesClienteId() {
	}

	public IdentificacionesClienteId(int idCliente, int idIdentificacion) {
		this.idCliente = idCliente;
		this.idIdentificacion = idIdentificacion;
	}

	@Column(name = "id_cliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "id_identificacion", nullable = false)
	public int getIdIdentificacion() {
		return this.idIdentificacion;
	}

	public void setIdIdentificacion(int idIdentificacion) {
		this.idIdentificacion = idIdentificacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IdentificacionesClienteId))
			return false;
		IdentificacionesClienteId castOther = (IdentificacionesClienteId) other;

		return (this.getIdCliente() == castOther.getIdCliente())
				&& (this.getIdIdentificacion() == castOther.getIdIdentificacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCliente();
		result = 37 * result + this.getIdIdentificacion();
		return result;
	}

}
