package net.netasystems.client.persistence.entities;
// Generated 27/09/2018 11:28:55 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdentificacionesCliente generated by hbm2java
 */
@Entity
@Table(name = "identificaciones_cliente", schema = "public")
public class IdentificacionesCliente implements java.io.Serializable {

	private IdentificacionesClienteId id;
	private Cliente cliente;
	private IdentificacionOficial identificacionOficial;
	private CatalogoGeneral catalogoGeneral;
	private String obs;
	private String usrCrea;
	private Date fchCrea;
	private String usrModi;
	private Date fchModi;

	public IdentificacionesCliente() {
	}

	public IdentificacionesCliente(IdentificacionesClienteId id, Cliente cliente,
			IdentificacionOficial identificacionOficial) {
		this.id = id;
		this.cliente = cliente;
		this.identificacionOficial = identificacionOficial;
	}

	public IdentificacionesCliente(IdentificacionesClienteId id, Cliente cliente,
			IdentificacionOficial identificacionOficial, CatalogoGeneral catalogoGeneral, String obs, String usrCrea,
			Date fchCrea, String usrModi, Date fchModi) {
		this.id = id;
		this.cliente = cliente;
		this.identificacionOficial = identificacionOficial;
		this.catalogoGeneral = catalogoGeneral;
		this.obs = obs;
		this.usrCrea = usrCrea;
		this.fchCrea = fchCrea;
		this.usrModi = usrModi;
		this.fchModi = fchModi;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCliente", column = @Column(name = "id_cliente", nullable = false)),
			@AttributeOverride(name = "idIdentificacion", column = @Column(name = "id_identificacion", nullable = false)) })
	public IdentificacionesClienteId getId() {
		return this.id;
	}

	public void setId(IdentificacionesClienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_identificacion", nullable = false, insertable = false, updatable = false)
	public IdentificacionOficial getIdentificacionOficial() {
		return this.identificacionOficial;
	}

	public void setIdentificacionOficial(IdentificacionOficial identificacionOficial) {
		this.identificacionOficial = identificacionOficial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus")
	public CatalogoGeneral getCatalogoGeneral() {
		return this.catalogoGeneral;
	}

	public void setCatalogoGeneral(CatalogoGeneral catalogoGeneral) {
		this.catalogoGeneral = catalogoGeneral;
	}

	@Column(name = "obs", length = 50)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "usr_crea", length = 20)
	public String getUsrCrea() {
		return this.usrCrea;
	}

	public void setUsrCrea(String usrCrea) {
		this.usrCrea = usrCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_crea", length = 35)
	public Date getFchCrea() {
		return this.fchCrea;
	}

	public void setFchCrea(Date fchCrea) {
		this.fchCrea = fchCrea;
	}

	@Column(name = "usr_modi", length = 20)
	public String getUsrModi() {
		return this.usrModi;
	}

	public void setUsrModi(String usrModi) {
		this.usrModi = usrModi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fch_modi", length = 35)
	public Date getFchModi() {
		return this.fchModi;
	}

	public void setFchModi(Date fchModi) {
		this.fchModi = fchModi;
	}

}
